#!/bin/sh

if [ ! $BASE_DIR ]
then
    . $(dirname $(readlink -f $0))/../scripts/bootstrap
fi

if [ ! "$(docker_sudo docker ps -a | grep sgaweb | grep app)" ]
then
    $SCRIPTS_DIR/build-container
fi

if [ ! -f $BASE_DIR/vendor ]
then
    $SCRIPTS_DIR/composer install
fi

if [ ! -e $BASE_DIR/.env ]
then
    $SCRIPTS_DIR/regenerate-key
fi

if [ "$(echo $1 | grep start)" ]
then
    $SCRIPTS_DIR/start-server
fi
