#!/bin/sh

EXPECTED_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi

if [ ! $COMPOSER_DIR ]
then
    . $(dirname $(readlink -f $0))/../scripts/bootstrap
fi

if [ ! -e $COMPOSER_DIR ]
then
    mkdir $COMPOSER_DIR
fi

php composer-setup.php --quiet --install-dir=$COMPOSER_DIR --filename=composer.phar
RESULT=$?
rm composer-setup.php
exit $RESULT
